config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'
  get 'messages/index'
  root 'messages#index'

  get '/signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/topics/new'
  #get 'topics/create'
  #get 'topics/show'
  #get 'topics/index'

  resources :users
  resources :messages
  resources :topics

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :topic

  validates :user_id, presence: true
  validates :topic_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }

end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :messages
  belongs_to :user

  validates :title, presence:true, length: {maximum:30}
  validates :user_id, presence:true
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :topics
  has_many :messages
  

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { within: 6..50 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # def self.authenticate(name, submitted_password)
  #    user = find_by_name(name)
  #    return nil  if user.nil?
  #    return user if user.password == submitted_password
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private   

  def signed_in_user
      unless signed_in?
        flash[:danger] = "Please log in."
        redirect_to signin_url
      end
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :signed_in_user, only: [:create]
  #before_filter :authenticate, :only => [:create]

  def create
    @message = Message.new(message_params)
    this_user = User.find_by_name current_user.name
    @message.user_id = this_user.id
    @message.topic_id = flash[:topic_id]

    if @message.save
      redirect_to :action => 'index'
    else
      flash[:messageFlash] = "Message didn't post!"
      render 'index'
    end
  end

  def index
    @title = "Message Board"
    @message = Message.all # :order => "created_at DESC",
               # :limit => 50
    @form_heading = "Write post"
    @new_message = Message.new
    @user = User.all
    @topic_list = Topic.all #, :order => "created_at DESC",
        #      :limit => 15
  end

  private

    def message_params
      params.require(:message).permit(:content, :user_id, :topic_id)
    end
    # def authenticate
    #   deny_access unless signed_in?
    # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash[:center] = "Sign in failed!"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create]
  #before_filter :authenticate, :only => [:new, :create]

  def new
    @title = "Make new Topic"
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    this_user = User.find_by_name current_user.name
    @topic.user_id = this_user.id

  if @topic.save
      redirect_to messages_path
    else
      flash[:center] = "No new Topic created!"
      render 'new'
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @title = @topic.title 
    @message = @topic.messages
    @form_heading = "Write post"
    @new_message = Message.new
    @user = User.all
    @topic_list = Topic.all #, :order => "created_at DESC",
                # :limit =>15
    flash[:topic_id] = @topic.id
  end

  def index
    @title = "Topics index"
    @topic = Topic.all #, :order => "created_at DESC"
    @user = User.all
  end


  private

  def topic_params
    params.require(:topic).permit(:title, :user_id)
  end
  #  def authenticate
  #    deny_access unless signed_in?
  #  end

   # def correct_user
   #   @user = User.find(params[:id])
    #  redirect_to(root_path) unless current_user?(@user)
   # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  #before_filter :authenticate, :only => [:edit,:update, :destroy]
  #before_filter :correct_user, :only => [:edit, :update, :destroy]

  def new
    @title = "Signup Page"
    @user = User.new
    end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to :action => 'index'
    else
      @title = 'Signup failed'
      flash[:center] = "Signup failed!"
      render 'new'
    end
  end

  def show
    @title = "User record"
    @user = User.find(params[:id])
  end


  def index
    @title = "List of users"
    @users = User.all
  end

  def edit
    @title = "Edit user info"
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:update] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :action => 'index'
  end


  private

    def user_params
      params.require(:user).permit(:name, :textColor, :font, :password,
                                    :password_confirmation)
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    # def authenticate
    #   deny_access unless signed_in?
    # end

    # def correct_user
    #   @user = User.find(params[:id])
    #   redirect_to(root_path) unless current_user?(@user)
    # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def sign_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user && user == current_user
  end

  #Returns true if the user is logged in, false otherwise.
  def signed_in?
    !current_user.nil?
  end

  # Signs out the current user.
  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--<link href='http://fonts.googleapis.com/css?family=Lora|Ubuntu|Bad+Script|Open+Sans|Coming+Soon|Fondamento' rel='stylesheet' type='text/css'>-->
  <title>Message Board | <%= @title %></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'styles_for_message_board', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
</head>

<body>
  <div class = "container">
    <div class="header">Message board</div>
    <div class="innerContainer"> 
      <div class="sidebar">
        <div class="nav">
          <ul>

          <li><%= link_to "Message Board", messages_path %></li>
          <li><%= link_to "User List", users_path  %></li>
          <li><%= link_to "Topic List", topics_path %> </li>
          <li><%= link_to "Sign up", new_user_path %></li>

          <% if signed_in? %>

            <li>
               <%= link_to "Make new Topic", new_topic_path %>
            </li>

            <li><%= link_to "Sign out", signout_path, 
                :method => :delete %>
            </li>

          <% else %>
            <li><% link_to "Sign in", signin_path %></li>
          <% end %>

          </ul>
        </div>

<%= yield %>

    </div> 
    <%# debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/messages/index.html.erb
<!-- Message index -->
  <div class="topics" id = "longTopics">
    <%= render :partial => "shared/topics" %>
  </div>

  <div class = "newMessage" >
  </div> 

</div>  <!-- Sidebar div closed -->


<div class="messageArea">

  <h4>Recent posts</h4>

    <% for message in @message %>

      <h4 class = "compact"> 
        <%= message.topic.title %>
      </h4>

      <div class = "message"
        style = "color: <%= message.user.textColor %>;
            font-family: <%= message.user.font %>;"
      >

      <p class="message">
          <%=  message.content %>
      </p>
  
      <p class = "info">
        #<%= message.id %> created <%= time_ago_in_words(message.created_at) %> ago
      </p>

      <p class ="author">
        <%= message.user.name %>
      </p>

      <span class="links">
        <% if signed_in? %>
          <%= link_to "Reply", topic_path(message.topic)%>
        <% end %>
      </span>

      </div>
      <br />
    <% end %>

</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_messageArea.html.erb
<%# Functionality to display messages%>
<%= render 'shared/message_error_messages' %>
    <!-- Error messages don't render. Fix this -->

    <% for message in @message %>
      
      <div class = "message"
        style = "color: <%= message.user.textColor %>;
            font-family: <%= message.user.font %>;"
      >
      
      <p class="message">
          <%=  message.content %>
      </p>
  
      <p class = "info">
        #<%= message.id %>
      </p>

      <p class ="author">
        <%= message.user.name %> posted <%= time_ago_in_words(message.created_at) %> ago
      </p>

      </div>
      <br />
    <% end %>

app/views/shared/_message_error_messages.html.erb
<% if @new_message.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@new_message.errors.count, "error") %> 
        prohibited this message from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @new_message.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_newMessage.html.erb
<%# Fuctionality to create new message %>
<%= form_for @new_message do |f|%>

  <div class="messageFlash"><%= flash[:messageFlash] %></div>

  <div class="messageForm">
    <%= f.label :content, "800 character maximum" %>
    <br>
    <%= f.text_area :content %>
  </div>

  <div>
    <br>
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/shared/_topics.html.erb
<%# Functionality for topic links list%>
<h4 class = "compact" >Recent topics</h4>
<ul class="compact" >
  <% for topic in @topic_list %>

    <li>
      <%= link_to topic.title, topic_path(topic) %>
    </li>
    
  <% end %>
</ul>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/index.html.erb
</div> <!-- Close sidebar div -->

  <div class="smallContainer" >
  <br>
  <h1>List of Topics</h1>

    <ul>
      <% for topic in @topic %>

      <li>
          <%= link_to topic.title, topic_path(topic) %>: was started at 
            <%= topic.created_at %> by <%= topic.user.name %>
      </li>

      <% end %>
    </ul>

<%= link_to "Make new Topic", new_topic_path %>
  </div>

app/views/topics/new.html.erb
</div> <!-- Close sidebar div -->

<div class = "smallContainer">
  <h1>Make new Topic</h1>
  <%= form_for @topic do |f|%>
    <ul class="form">

      <li>
        <%= f.label :title, "Topic title, 25 character maximum" %>
        <br />
        <%= f.text_field :title %>
      </li>

      <li>
        <%= f.submit "Submit" %>
      </li>

    </ul>
  <% end %>

  <div class="centerFlash"><%= flash[:center] %></div>

</div>

app/views/topics/show.html.erb
  <div class = "topics">
    <%= render :partial => "shared/topics" %>
  </div>

  <div class = "newMessage" >
    <%= render :partial => "shared/newMessage" %>
  </div>

</div>  <!-- Sidebar div closed -->

<div class = "messageArea">

  <h4> <%= @title %> </h4>

    <%= render :partial => "shared/messageArea" %>
</div>

app/views/users/_selectFontAndTextColor.html.erb
    <li>
      <%= f.label :font, "Select your font" %><br />
      <%= f.select :font,
        options_for_select([
                ["Bad Script","'Bad Script', cursive"],
                ["Coming Soon","'Coming Soon', cursive"],
                ["Fondamento","'Fondamento', cursive"],
                ["Lora","'Lora', serif"],
                ["Open Sans","'Open Sans', sans-serif"],
                ["Ubuntu","'Ubuntu', sans-serif"]
        ].shuffle )%>
    </li>



    <li>
      <%= f.label :textColor, "Select your color"%><br />
      <%= f.select :textColor,
       %w( aqua olive orange red silver teal yellow white ).shuffle %>
    </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user info") %>
</div> <!-- Close sidebar div -->

<div class="smallContainer">
  <h1>Edit settings for <%= @user.name %></h1>
  <%= form_with(model: @user, local: true) do |f| %>
  <ul class="form">
    
    <%= render partial: 'selectFontAndTextColor',
                        locals: { :f => f } %>

    <li><br /><%= f.submit "Submit" %></li>
  </ul>
  <% end %>


<div>
  <%= link_to "User index", users_path %>
</div>

</div>

app/views/users/index.html.erb
</div> <!-- Close sidebar div -->
  <div class="smallContainer" >
    <br>
    <h1>List of users</h1>

    <%# will_paginate %>
    <ul>
      <% for user in @users %>
      <li style = "color: <%= user.textColor %>; 
            font-family: <%= user.font %>;">

      User <%= user.name %> writes <%= user.textColor %> text in <%=
         user.font %> font. 

        <% if  current_user?(user) %>
        &nbsp; <%= link_to "show", :controller => "users",
            :action => "show", :id => user.id %>
        &nbsp; <%= link_to "edit", :controller => "users",
            :action => "edit", :id => user.id %>
        &nbsp; <%= link_to "destroy", :controller => "users",
            :action => "destroy", :id => user.id %>
        <% end %>

      </li>
      <% end %>
    </ul>
    <%# will_paginate %>

    <%= link_to "New user signup", new_user_path %>
  </div>

app/views/users/new.html.erb
</div> <!-- Close sidebar div -->

<%= render 'shared/error_messages' %>

<div class="smallContainer">
  <h1>New member signup</h1>

  <%= form_for(@user) do |f| %>
  <ul class="form">
    <li><%= f.label :name, "Your screen name"%><br />
        <%= f.text_field :name %> </li> 

    <%= render :partial => 'selectFontAndTextColor',
                        :locals => { :f => f } %>

    <li><%= f.label :password, 
          "Enter password, minimum 6 characters" %>
        <br /> <%= f.password_field :password %></li>

    <li><%= f.label :password_confirmation, 
                "Enter password again" %>
        <br /><%= f.password_field :password_confirmation %></li>

    <li><%= f.submit "Submit" %></li>
  </ul>
  <% end %>

  <p>
    Fonts: <span style="font-family: Bad Script; color: red;">Bad Script, </span>
    <span style="font-family: Coming Soon; color: olive;">Coming Soon, </span>
    <span style="font-family: Fondamento; color: silver;">Fondamento, </span>
    <span style="font-family: Lora; color: yellow;">Lora, </span>
    <span style="font-family: Open Sans; color: teal;">Open Sans, </span>
    <span style="font-family: Ubuntu; color: orange;">Ubuntu </span>
  </p>

  <div class="centerFlash"><%= flash[:center] %></div>
  <%= debug(params) if Rails.env.development? %>
</div>

app/views/users/show.html.erb
</div> <!-- Close sidebar div -->

<div class="smallContainer">
  <h1>User <%= @user.name %></h1>
  <ul>
    <li>Text color: <%= @user.textColor %></li>
    <li>Font : <%= @user.font %></li>
  </ul>

  <br />
  <div>
    <%= link_to "Edit user settings", edit_user_path(current_user) %>
    <br>
    <%= link_to "User index", users_path %>
  </div>
</div>